name: Convert JPG -> AVIF (otm + tmb)

on:
  push:
    paths:
      - 'img/**'

jobs:
  convert:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run AVIF conversion script
        run: node scripts/convert-images.js

      - name: Commit & push generated AVIFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add img/otm img/tmb || true
          if git diff --cached --quiet; then
            echo "No new AVIF files to commit."
          else
            git commit -m "chore: add generated AVIF images [skip ci]" || echo "Nothing to commit"
            git push origin HEAD
          fi
